files:
  operation_params.mustache:
    templateType: API
    destinationFilename: Params.kt
  room.mustache:
    templateType: SupportingFiles
    destinationFilename: Room.kt
    folder: com/expediagroup/sdk/xap/model
  get_flight_listings_operation_segment_param.mustache:
    templateType: SupportingFiles
    destinationFilename: GetFlightListingsOperationSegmentParam.kt
    folder: com/expediagroup/sdk/xap/model
