/*
 * Copyright (C) 2022 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.expediagroup.sdk.xap.models

import com.expediagroup.sdk.xap.models.RatingDetails
import com.fasterxml.jackson.annotation.JsonProperty
import org.hibernate.validator.constraints.Length
import javax.validation.Valid
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

/**
 * The rating of the car being offered.
 * @param ratingPercentage The percentage of rating.
 * @param ratingCount The total count of rating.
 * @param ratingDetails List of all the details of rating.
 */
data class Rating(
    // The percentage of rating.
    @JsonProperty("RatingPercentage")
    @field:Valid
    val ratingPercentage: kotlin.String,
    // The total count of rating.
    @JsonProperty("RatingCount")
    @field:Valid
    val ratingCount: kotlin.String,
    // List of all the details of rating.
    @JsonProperty("RatingDetails")
    @field:Valid
    val ratingDetails: kotlin.collections.List<RatingDetails>? = null
) {
    companion object {
        @JvmStatic
        fun builder() = Builder()
    }

    class Builder(
        private var ratingPercentage: kotlin.String? = null,
        private var ratingCount: kotlin.String? = null,
        private var ratingDetails: kotlin.collections.List<RatingDetails>? = null
    ) {
        fun ratingPercentage(ratingPercentage: kotlin.String) = apply { this.ratingPercentage = ratingPercentage }

        fun ratingCount(ratingCount: kotlin.String) = apply { this.ratingCount = ratingCount }

        fun ratingDetails(ratingDetails: kotlin.collections.List<RatingDetails>?) = apply { this.ratingDetails = ratingDetails }

        fun build(): Rating {
            // Check required params
            validateNullity()
            return Rating(
                ratingPercentage = ratingPercentage!!,
                ratingCount = ratingCount!!,
                ratingDetails = ratingDetails
            )
        }

        private fun validateNullity() {
            if (ratingPercentage == null) {
                throw NullPointerException("Required parameter ratingPercentage is missing")
            }
            if (ratingCount == null) {
                throw NullPointerException("Required parameter ratingCount is missing")
            }
        }
    }

    fun toBuilder() =
        Builder(
            ratingPercentage = ratingPercentage!!,
            ratingCount = ratingCount!!,
            ratingDetails = ratingDetails
        )
}
