name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test-xap-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build and Test
        run: ./gradlew clan build

  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Integration Tests
        uses: ./.github/workflows/run-integration-tests.yaml
        with:
          branch: main
          jdk: '8'
          distribution: 'corretto'

