name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test-xap-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: corretto

      - name: Build and Test
        run: ./gradlew clean build

  run-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yaml
    with:
      branch: ${{ github.ref }}
      jdk: 11
      distribution: corretto

