name: Generate and Publish SDK Sources

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          SDK Version.
          E.g., 1.0.0, 1.0.1, 1.0.0-SNAPSHOT, etc.
        required: true
        type: string

jobs:
  generate-and-publish-sources:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-full-workflow.yaml@nanssari/update_transform_action
    secrets: inherit
    with:
      name: xap
      ref: ${{ github.head_ref || github.ref_name }}
      repository: 'ExpediaGroup/xap-java-sdk'
      sdk_repo_ref: 'v20250304'
      transformations: '--headers accept,accept-encoding,key --operationIdsToTags --defaultStringType QUOTE_SINGLE'
      version: ${{ inputs.version }}
