name: Generate and Publish SDK Sources

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          SDK Version.
          E.g., 1.0.0, 1.0.1, 1.0.0-SNAPSHOT, etc.
        required: true
        type: string

jobs:
  generate-and-publish-sources:
    uses: ExpediaGroup/expediagroup-java-sdk/.github/workflows/selfserve-full-workflow.yaml@v20241126
    secrets: inherit
    with:
      name: xap
      version: ${{ inputs.version }}
      transformations: "--headers key --operationIdsToTags"
      repository: 'ExpediaGroup/xap-java-sdk'
      ref: ${{ github.head_ref || github.ref_name }}
