name: Deploy Reference Documentation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to deploy reference docs from. Defaults to current branch.'
        type: string
        required: false
        default: ''

permissions:
  id-token: write

jobs:
  deploy-reference-docs:
    uses: "ExpediaGroup/expediagroup-java-sdk/.github/workflows/generate-ref-docs.yaml@feature/new-sdk-core"
    with:
      ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
      sources_dir: 'xap-sdk'
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
