name: Integration Tests

on:
  workflow_call:
    inputs:
      jdk:
        description: 'JDK version to use'
        required: true
        type: string
      distribution:
        description: 'JDK distribution to use'
        required: false
        type: string
        default: 'corretto'
      branch:
        description: 'Branch to build SDK and run integration tests from'
        required: true
        type: string

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 21
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: 'ExpediaGroup/xap-java-sdk'
          ref: ${{ inputs.branch }}
          path: sdk-repo

      - name: Parse SDK version
        id: parse-sdk-version
        working-directory: sdk-repo/code
        shell: python -u {0}
        run: |
          import os
          import xml.etree.ElementTree as ET

          tree = ET.parse("pom.xml")
          root = tree.getroot()
          version = root.find("{*}version").text

          with open(os.getenv("GITHUB_OUTPUT"), "a") as GITHUB_OUTPUT:
            print(f"version={version}", file=GITHUB_OUTPUT)

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.jdk }}

#      - id: set-java-home
#        run: |
#          echo "JAVA_HOME_RUN=$JAVA_HOME_${{ inputs.jdk }}_${{ runner.arch }}" >> $GITHUB_OUTPUT
#          echo "JAVA_HOME_INSTALL=$JAVA_HOME_${{ env.JAVA_VERSION }}_${{ runner.arch }}" >> $GITHUB_OUTPUT

      - name: Install SDK
        working-directory: sdk-repo/code
#        env:
#          JAVA_HOME: ${{ steps.set-java-home.outputs.JAVA_HOME_INSTALL }}
        run: |
          mvn clean install

      - name: Run Integration Tests
        working-directory: sdk-repo/tests/integration
#        env:
#          JAVA_HOME: ${{ steps.set-java-home.outputs.JAVA_HOME_RUN }}
        run: |
          mvn verify \
            -Dmaven.license.plugin.skip=true \
            -Dxap-java-sdk.sdk.version="${{ steps.parse-sdk-version.outputs.version }}"
