name: Manual Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
#  run-examples:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run Examples
#        uses: ./.github/workflows/run-examples.yaml
#        with:
#          branch: main
#          jdk: 11
#          distribution: corretto

  run-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yaml
    with:
      branch: main
      jdk: 11
      distribution: corretto

  publish-to-maven-central:
    runs-on: ubuntu-latest
    needs: [run-integration-tests]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: corretto

      - name: Build and Test
        run: ./gradlew clean build

      - name: Publish xap-sdk module
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          echo "Publishing xap-sdk"
          ./gradlew :xap-sdk:publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: Publish Summary
        run: |
          echo "✅ Successfully published xap-sdk to Maven Central" >> $GITHUB_STEP_SUMMARY
