name: Release SDK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: |
          Branch to release the SDK from.
          Defaults to the branch the action is being run from.
        type: string
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Publish SDK
        working-directory: xap-sdk
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          version="${{ github.event.inputs.version }}"
          version="${version// /}"
          if [[ "$version" == *"-SNAPSHOT" ]]; then
            gradle publishSnapshot -PVERSION="${version}"
          else
            gradle publishToSonatype closeAndReleaseSonatypeStagingRepository -PVERSION="${version}"
          fi
