name: Run Examples

on:
  workflow_dispatch:
    inputs: &shared_inputs
      jdk:
        description: 'JDK version to use'
        required: true
        type: string
      distribution:
        description: 'JDK distribution to use'
        required: false
        type: string
        default: 'corretto'
      branch:
        description: 'Branch to build SDK and run examples from'
        required: true
        type: string

  workflow_call:
    inputs: *shared_inputs

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.jdk }}
          distribution: ${{ inputs.distribution }}

      - name: Run Examples
        env:
          XAP_KEY: "${{ secrets.API_KEY }}"
          XAP_SECRET: "${{ secrets.API_SECRET }}"
          VRBO_KEY: "${{ secrets.VRBO_KEY }}"
          VRBO_SECRET: "${{ secrets.VRBO_SECRET }}"
        run: |
          ./gradlew :examples:run
