name: Run Examples
on:
  workflow_call:
    inputs:
      jdk:
        description: 'JDK version to use'
        required: true
        type: string
      distribution:
        description: 'JDK distribution to use'
        required: false
        type: string
        default: 'corretto'
      branch:
        description: 'Branch to build SDK and run examples from'
        required: true
        type: string

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.jdk }}
          distribution: ${{ inputs.distribution }}

      - name: Install SDK
        working-directory: sdk-repo/code
        run: |
          mvn clean install

      - name: Run Examples
        working-directory: sdk-repo/examples
        run: |
          mvn install exec:java \
            -Dexec.mainClass="com.expediagroup.sdk.xap.examples.XapSdkDemoTestRun" \
            -Dcom.expediagroup.xapjavasdk.apikey="${{ secrets.API_KEY }}" \
            -Dcom.expediagroup.xapjavasdk.apisecret="${{ secrets.API_SECRET }}" \
            -Dcom.expediagroup.xapjavasdk.vrbokey="${{ secrets.VRBO_KEY }}" \
            -Dcom.expediagroup.xapjavasdk.vrbosecret="${{ secrets.VRBO_SECRET }}" \
            -Dxap-java-sdk.sdk.version="${{ steps.parse-sdk-version.outputs.version }}"
