name: Verify Examples and Integration Tests
on:
  push:
    branches:
      - "mdwairi/move-integration-tests"
  pull_request:
    branches:
      - 'main'
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      examples: ${{ steps.filter.outputs.examples }}
      integration-tests: ${{ steps.filter.outputs.integration-tests }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            examples:
              - 'examples/**'
            integration-tests:
              - 'integration-tests/**'

  verify-examples:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.examples == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: verify examples
        run: |
          ./gradlew :examples:run \
            -Dcom.expediagroup.xapjavasdk.apikey="${{ secrets.API_KEY }}" \
            -Dcom.expediagroup.xapjavasdk.apisecret="${{ secrets.API_SECRET }}" \
            -Dcom.expediagroup.xapjavasdk.vrbokey="${{ secrets.VRBO_KEY }}" \
            -Dcom.expediagroup.xapjavasdk.vrbosecret="${{ secrets.VRBO_SECRET }}" \

  verify-integration-tests:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.integration-tests == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: verify integration tests
        run: |
          ./gradlew :integration-tests:test
