name: Verify Examples and Integration Tests
on:
  push:
    branches:
      - "mdwairi/move-integration-tests"
  pull_request:
    branches:
      - 'main'
jobs:
  verify-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: verify examples
        env:
          XAP_KEY: "${{ secrets.API_KEY }}"
          XAP_SECRET: "${{ secrets.API_SECRET }}"
          VRBO_KEY: "${{ secrets.VRBO_KEY }}"
          VRBO_SECRET: "${{ secrets.VRBO_SECRET }}"
        run: |
          ./gradlew :examples:run

  verify-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: verify integration tests
        run: |
          ./gradlew :integration-tests:test
